# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 231c15086048f0eb5b96aa744400b9c9cf3ac03bb17213f5d4b261c65c12e71b2804c8100e43e4b6f0d4055fd4870e4a3057e2e0babd820cc57e790ed5604a89

test:
  secret_key_base: fd89849904414f0dfd53ba8cabd74613a9ecfdb6da030db7ac7923fe104397dc8a8332b5639c1e689ca1c512f39dae50976f68a115fc5445a99fe9d32c65cf14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
